require 'hoe'


Hoe.spec 'fbtxt2json' do
  self.version = '0.3.0'

  self.summary = "fbtxt2json (& fbtxt2csv) - convert football.txt match schedules & more to (structured) json or (tabular) csv"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/footty' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']


  self.extra_deps = [
       ['sportdb-quick',  '>= 0.7.0'],
       ['sportdb-parser', '>= 0.7.1'],
       ### note - include fbtok gem for (shared) command-line helpers/machinery!!!
       ['fbtok', '>= 0.4.1'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
